### ISSUE TITLE
CSS Improvement Suggestion for Compact Mode

### ISSUE THREAD

**Issue by jstueckrath** [gatanaso/multiselect-combo-box#62]
I noticed that the compact mode layout is not consistent with the standard layout and would therefore suggest the following CSS changes (which I also used in my project):

```CSS
[part="compact-mode-label"] {
	margin: var(--lumo-space-xs);
	color: var(--lumo-body-text-color);
	font-weight: 500;
	padding: 0 calc(0.375em + var(--lumo-border-radius)/4 - 1px);
}
```

The color and font-weight above are the same as the ones used in non-compact mode. The margin will prevent the combo box from being larger in compact mode compared to non-compact mode (as it currently is, see below). The padding makes no difference in my example, but I took it from the Textfield definition and think it is more flexible.

See the changes below compared to other fields (layouted by Chromium). Note that I am still using the Vaadin standard layouts.

Before:
![Layout Compare Before](https://user-images.githubusercontent.com/38353563/77298024-76d46700-6cea-11ea-937e-4a0d132fa73e.PNG)

After:
![Layout Compare After](https://user-images.githubusercontent.com/38353563/77298034-7b008480-6cea-11ea-977f-8eddcbf5705c.PNG)
